Demo.WebUI/Controllers/CartController.cs
using Demo.Domain.Abstract;
using Demo.Domain.Entities;
using Demo.WebUI.Models;
using Demo.WebUI.Ultilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Demo.WebUI.Controllers
{
    public class CartController : Controller
    {
        //khai báo repository
        private readonly IMainRepository _mainRepository;

        //inject
        public CartController(IMainRepository mainRepository)
        {
            _mainRepository = mainRepository;
        }
        // GET: Cart
        public ViewResult Index()
        {
            var cart = GetCart();

            return View(cart);//show cart lên view
        }
        //[HttpPost]
        //public ActionResult AddToCart(AddToCartModel model) //model binding
        //{
        //    //kiem tra xem sản phẩm có tồn kho hay không tùy vào nghiệp vụ
        //    var product = _mainRepository
        //     .Products
        //     .FirstOrDefault(x => x.ProductId == model.ProductId);

        //    if (product != null)
        //    {
        //        //add to cart
        //        var cart = GetCart();
        //        cart.Add(product, model.Quantity);
        //    }
        //    return RedirectToAction("Index");
        //}
        //private Cart GetCart()
        //{
        //    //lấy giỏ hàng từ session
        //    var cart = Session["cart"] as Cart;
        //    //chưa có giỏ hàng
        //    if(cart == null)
        //    {
        //        //khởi tạo
        //        cart = new Cart();
        //        //lưu vào session
        //        Session["cart"] = cart;
        //    }
        //    return cart;
        //}

        //xử lí json
        [HttpPost]
        //public ActionResult AddToCart(int productId, int quantity) //nếu không sử dụng model binding thì sẽ như vầy 
        //public ActionResult AddToCart(AddToCartModel model)// model binding khai báo model ở đây và ràng buộc dữ liệu trong model
        public JsonResult AddToCartJson(AddToCartModel model)
        {
            
            if(ModelState.IsValid)// check model có hợp lệ hay không => tác dụng của model binding
            {
                var product = _mainRepository.Products.FirstOrDefault(x => x.ProductId == model.ProductId);
                if (product != null)
                {
                    var cart = GetCart();
                    cart.Add(product, model.Quantity);
                    return Json(new { state = true, msg = "thanh cong" });
                    
                }
            }

            var data = (new { state = false, msg = " khong thanh cong" });
            return Json(data);// ở đây không cần AllowGet vì mặc định của return Json là Post mà action này mình đã khai báo HttpPost rồi nên return Post mặc định là correct
            //return RedirectToAction(nameof(CartController.Index));
        }

        [HttpPost]
        public JsonResult RemoveFromCartJson(int productId)
        {
            
            var product = _mainRepository.Products.FirstOrDefault(x => x.ProductId == productId);
            if(product != null)
            {
                var cart = GetCart();
                cart.Remove(product);
                return Json(new { state = true, msg = "xoa thanh cong" });
                
            }

            var data1 = (new { state = false, msg = "xoa that bai" });
            return Json(data1);
        }

        [HttpPost]
        //public ActionResult AddToCart(int productId, int quantity) //nếu không sử dụng model binding thì sẽ như vầy 
        public JsonResult UpdateToCartJson(AddToCartModel model)// model binding khai báo model ở đây và ràng buộc dữ liệu trong model
        {
            
            if (ModelState.IsValid)// check model có hợp lệ hay không => tác dụng của model binding
            {
                var product = _mainRepository.Products.FirstOrDefault(x => x.ProductId == model.ProductId);
                if (product != null)
                {
                    var cart = GetCart();
                    cart.Update(product, model.Quantity);
                    return Json(new { state = true, msg = "update thanh cong" });
                    
                }
            }
            return Json(new { state = false, msg=""});
            
        }
        public PartialViewResult CartSummary()
        {
            var cart = GetCart();
            return PartialView(cart);
        }
        public PartialViewResult BodySummary()
        {
            var cart = GetCart();
            return PartialView(cart);
        }
        public ActionResult CheckOut()
        {
            //var cart = GetCart();
            //nếu giỏ hàng rỗng
            //if(cart.Lines.Count()==0)
            //{
            //    return RedirectToAction(nameof(CartController.Index));
            //}
            //ViewBag.Cart = cart;
            ViewBag.Payments = _mainRepository.Payments.ToList();// nhận giá trị là 1 list 
            return View();
        }

        [HttpPost]
        public ActionResult CheckOut(CartCheckOutModel model)
        {
            var cart = GetCart();
            if(cart.Lines.Count()==0)
            {
                ModelState.AddModelError("", "giỏ hàng rỗng vui lòng chọn sản phẩm cần mua");
            }
            


            //kiểm tra tính hợp lệ hay không
            if(ModelState.IsValid)
            {
                //add dữ liệu vào database
                var khachHang = new KhachHang()
                {
                    DiaChi = model.Address,
                    Email = model.Email,
                    DienThoai = model.Phone,
                    TenKhachHang = model.FullName
                };
                _mainRepository.Add(khachHang);
                var donHang = new DonHang()
                {
                    GhiChu = model.Note,
                    MaKhachHang = khachHang.MaKhachHang,
                    NgayTao = DateTime.Now,
                    Ship = model.UseShipper
                };
                _mainRepository.Add(donHang);
                foreach (var item in cart.Lines)
                {
                    var chiTiet = new ChiTietDonHang
                    {
                        GiaTien = item.Product.Price,
                        SoLuong = item.Quantity,
                        MaDonHang = donHang.MaDonHang,
                        MaSanPham = item.Product.ProductId
                    };
                    _mainRepository.Add(chiTiet);
                }



                //gửi email: nội dung, chủ đề , người nhận
                //xây dựng nội dung
                StringBuilder sb = new StringBuilder();
                sb.Append("<table>");
                //full name
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("Khách hàng");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.FullName);
                sb.Append("</td>");
                sb.Append("</tr>");

                //email
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("Email");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.Email);
                sb.Append("</td>");
                sb.Append("</tr>");
                //điện thoại
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("ĐIện thoại");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.Phone);
                sb.Append("</td>");
                sb.Append("</tr>");
                ///địa chỉ
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("Khách hàng");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.FullName);
                sb.Append("</td>");
                sb.Append("</tr>");
                //thanh toán
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("Khách hàng");
                sb.Append("</td>");
                var payment = _mainRepository.Payments.FirstOrDefault(x => x.PaymentId== model.PaymentMethod);
                sb.Append("<td>");
                sb.Append(payment.PaymentName);// ở đây phải như vầy vì truyền lên client chỉ có Id nên phải xài như vầy
                sb.Append("</td>");
                sb.Append("</tr>");
                //ghi chú
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("ghi chú");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.Note);
                sb.Append("</td>");
                sb.Append("</tr>");
                
                //ship
                sb.Append("<tr>");
                sb.Append("<td>");
                sb.Append("Ship tận nhà");
                sb.Append("</td>");
                sb.Append("<td>");
                sb.Append(model.UseShipper ? ": Có." : ": Không.");
                sb.Append("</td>");
                sb.Append("</tr>");
                sb.Append("</table>");

                var sender = new EmailSender();
                sender.Send("thông báo đặt hàng", sb.ToString(), model.Email);
                return Redirect("/"); // về trang chủ nếu gửi mail thành công (ModelStates.isValid ==ok)
            }
            ViewBag.Payments = _mainRepository.Payments.ToList();// nhận giá trị là 1 list 
            return View(model);// nếu không guwridduwojc thì trả lại view này
        }

        #region Helper
        private Cart GetCart()
        {
            //lấy giỏ  hàng từ session
            var cart = Session["cart"] as Cart;
            //chưa có giỏ hàng
            if (cart == null)
            {
                //khởi tạo
                cart = new Cart();

Demo.WebUI/Controllers/HomeController.cs
using Demo.Domain.Abstract;
using Demo.Domain.Concrete;
using Demo.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.WebUI.Controllers
{
    public class HomeController : Controller
    {
        //khai báo repository
        private readonly IMainRepository _mainRepository;

        //inject
        public HomeController(IMainRepository mainRepository)
        {
            _mainRepository = mainRepository;
        }

        //abcs zuxux
        public ViewResult Index()
        {
            HomeIndexViewModel model = new HomeIndexViewModel();

            model.Products = _mainRepository.Products
                .OrderByDescending(x => x.ProductId)
                .Take(3)
                .ToList();

            return View(model);
        }
        public ViewResult ListProduct(int page=1, int pageSize=10, int category=-1)
        {
            HomeListProductViewModel model = new HomeListProductViewModel();
            model.Products = _mainRepository.Products
                .Where(x=>category==-1 || x.CategoryId== category)
                .OrderByDescending(x=>x.ProductId)
                .Skip((page-1)*pageSize)
                .Take(pageSize)
                .ToList();
            model.PagingInfo = new PagingInfo()
            {
                CurentPage = page,
                PageSize = pageSize,
                TotalItems = _mainRepository.Products
                .Where(x=>category==-1 || x.CategoryId== category)
                .Count()
            };
            model.Categories = _mainRepository.Categories.ToList();
            model.CurrentCategory = category;
            return View(model);
        }
        public ViewResult ListCustomer(int page=1,int pageSize=3, int province=-1)
        {
            HomeListCustomerViewModel model = new HomeListCustomerViewModel();
            model.Customers = _mainRepository.Customers
                .Where(x => province == -1 || x.ProvinceId == province)
                .OrderBy(x=>x.ProvinceId)
                .Skip((page-1)*pageSize)
                .Take(pageSize)
                .ToList();
            model.PagingInfo = new PagingInfo()
            {
                CurentPage = page,
                PageSize = pageSize,
                TotalItems = _mainRepository.Customers
                .Where(x=>province==-1||x.ProvinceId==province)
                .Count()
            };
            model.Provinces = _mainRepository.Provinces.ToList();
            model.CurrentProvince = province;
            return View(model);
        }
        public ActionResult test()
        {
            ViewBag.Message = "Your applicađâsdasdasdasdastion description page.";
            
            return View();
        }
        //commit test
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //demo josn
        public JsonResult GetProduct(int id)
        {
            var product = _mainRepository.Products
                .Select(x => new { x.ProductId, x.Price, x.ProductName, x.Amount }) // vì product có tạo khóa ngoại nên nếu không select sẽ tạo ra vòng lặp vô hạn ở đây
                .FirstOrDefault(x => x.ProductId == id);
            return Json(product, JsonRequestBehavior.AllowGet);// allowget ở đây để đánh dấu là get vì Json mặc định là post nên muốn đánh dấu ở đây là get thì phải alowget
        }
        public JsonResult GetListProduct()
        {
            var products = _mainRepository.Products
                .Select(x=> new { x.ProductId, x.Price, x.ProductName, x.Amount})
                .Take(5).ToList();
            return Json(products, JsonRequestBehavior.AllowGet);
        }

    }
}

Demo.WebUI/Views/Home/Index.cshtml
@model Demo.WebUI.Models.HomeIndexViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Chào bạn đây là view index Home</h1>
<div class="card-deck mb-3 text-center">
    @foreach (var product in Model.Products)
    {
        @Html.Partial("_ProductSummary", product)
    }
</div>



@section js{
    <script>
        console.log('index page');
    </script>
}

Demo.WebUI/Views/Home/ListCustomer.cshtml
@model Demo.WebUI.Models.HomeListCustomerViewModel
@{
    ViewBag.Title = "ListCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-12 col-md-3">
        <div class="list-group">
            @foreach(var province in Model.Provinces)
            {
                <a href="@Url.Action("ListCustomer", "Home", new { province=province.ProvinceId})" class="list-group-item">
                    @province.ProvinceName
                </a>
            }
        </div>
    </div>
    <div class="col-12 col-md-9">
        <h2>ListCustomer</h2>
        <div class="card-deck mb-3 text-center">
            @foreach (var customer in Model.Customers)
            {
                @Html.Partial("_CustomerSummary", customer)
            }
        </div>


        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.PagingInfo.CurentPage > 1)
                {
                    <li class="page-item"><a class="page-link" href="@Url.Action("ListCustomer", "Home", new { Page= Model.PagingInfo.CurentPage-1, pageSize=Model.PagingInfo.PageSize, category= Model.CurrentProvince})">Previous</a></li>
                }

                @for (int i = 1, n = Model.PagingInfo.TotalPages; i <= n; i++)
                {
                    <li class="page-item  @(i == Model.PagingInfo.CurentPage ? "active":"")">
                        <a class="page-link" href="@Url.Action("ListCustomer", "Home", new { page=i , pageSize=Model.PagingInfo.PageSize, province= Model.CurrentProvince})">@i</a>
                    </li>
                }
                @if (Model.PagingInfo.CurentPage < Model.PagingInfo.TotalPages)
                {
                    <li class="page-item"><a class="page-link" href="@Url.Action("ListCustomer", "Home", new { Page= Model.PagingInfo.CurentPage+1, pageSize=Model.PagingInfo.PageSize, province= Model.CurrentProvince})">Next</a></li>
                }

            </ul>
        </nav>

    </div>
</div>

Demo.WebUI/Views/Home/ListProduct.cshtml
@model Demo.WebUI.Models.HomeListProductViewModel
@{
    ViewBag.Title = "ListProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12 col-md-3">
        <div class="list-group">
            @foreach (var category in Model.Categories)
            {
                <a href="@Url.Action("ListProduct","Home",new { category = category.CategoryId })"
                   class="list-group-item">
                    @category.CategoryName
                </a>
            }
        </div>

    </div>
    <div class="col-12 col-md-9">

        <div class="card-deck mb-3 text-center">
            @foreach (var product in Model.Products)
            {
                @Html.Partial("_ProductSummary", product)//gọi partial view ko cần action
            }
        </div>

        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.PagingInfo.CurentPage > 1)
                {
                    <li class="page-item"><a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = Model.PagingInfo.CurentPage - 1, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">Previous</a></li>
                }

                @*@for (int i = 1, n = Model.PagingInfo.TotalPages; i <= n; i++)
                    {
                        <li class="page-item @(i == Model.PagingInfo.Page ? "active" : "")">
                            <a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = i, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">@i</a>
                        </li>
                    }*@

                @if (Model.PagingInfo.CurentPage - 2 > 0 && Model.PagingInfo.CurentPage + 2 < Model.PagingInfo.TotalPages + 1)
                {
                    for (int i = Model.PagingInfo.CurentPage - 2; i < Model.PagingInfo.CurentPage + 3; i++)
                    {
                        <li class="page-item @(i == Model.PagingInfo.CurentPage ? "active" : "")">
                            <a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = i, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">@i</a>
                        </li>
                    }
                }

                @if (Model.PagingInfo.CurentPage == 1 || Model.PagingInfo.CurentPage == 2)
                {
                    for (int i = 1; i < 6; i++)
                    {
                        <li class="page-item @(i == Model.PagingInfo.CurentPage ? "active" : "")">
                            <a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = i, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">@i</a>
                        </li>
                    }
                }

                @if (Model.PagingInfo.CurentPage == Model.PagingInfo.TotalPages || Model.PagingInfo.CurentPage == Model.PagingInfo.TotalPages - 1)
                {
                    for (int i = Model.PagingInfo.TotalPages - 5; i < Model.PagingInfo.TotalPages + 1; i++)
                    {
                        <li class="page-item @(i == Model.PagingInfo.CurentPage ? "active" : "")">
                            <a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = i, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">@i</a>
                        </li>
                    }
                }

                @if (Model.PagingInfo.CurentPage < Model.PagingInfo.TotalPages)
                {
                    <li class="page-item"><a class="page-link" href="@Url.Action("ListProduct", "Home", new { page = Model.PagingInfo.CurentPage + 1, pageSize = Model.PagingInfo.PageSize, category = Model.CurrentCategory })">Next</a></li>
                }
            </ul>
        </nav>

    </div>
    @*<table>
        <tr>
            <td colspan="4" class="text-center">
                <nav>
                    <ul class="pagination">
                        @Html.PageLinks(Model.PagingInfo, x=>Url.Action("ListProduct",
                       new {
                           Page=x
                       }))
                    </ul>
                </nav>
            </td>
        </tr>
    </table>
</div>*@
</div>
@Html.PageLinks(Model.PagingInfo,
    x => Url.Action("ListProduct", "Home", new {
    page = x,
    pageSize = Model.PagingInfo.PageSize,
    category = Model.CurrentCategory
}))

Demo.WebUI/Views/Home/NewTestGit.cshtml
@{
    ViewBag.Title = "NewTestGit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>NewTestGit</h2>

<p>ViewBag.Message</p>

Demo.WebUI/Views/Home/_CustomerSummary.cshtml
@model Demo.Domain.Entities.Customer


<div class="card mb-4 shadow-sm">
    <div class="card-body">
        <img src="@Model.Avatar"
             class="img-fluid" />
        <p>@Model.CustomerId</p>

        <h3 class="card-title pricing-card-title">
            @Model.CustomerName
        </h3>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">
            Add To Card
        </button>
    </div>
</div>

Demo.WebUI/Views/Home/_ProductSummary.cshtml
@model Demo.Domain.Entities.Product

<div class="card mb-4 shadow-sm">
    <div class="card-body">
        <img src="@Model.ProductImage"
             class="img-fluid" />

        <h3 class="card-title pricing-card-title">
            @Model.ProductName
        </h3>

        @*@using (Html.BeginForm("AddToCart","Cart", FormMethod.Post , new { @class="frmForm"}))
        {
            <input class="form-control" type="number" value="1" min="1" max="10" name="Quantity"/>
            <input name="ProductId" value="@Model.ProductId" type="hidden" />
            <button type="submit" class="btn btn-outline-primary">
                Add
            </button>
        }*@

        @using (Html.BeginForm("AddToCartJson", "Cart", FormMethod.Post, new { @class="frmAddToCart" }))
        {
            <input name="ProductId" value="@Model.ProductId" type="hidden"/>// để ProductId và Quantity vì bên model ta viết hoa nên t nên để viết hoa ở đây
            @Html.TextBox("productId", Model.ProductId, new { type="hidden"})
            <input name="Quantity" value="1" type="number"/>
            <button type="submit" class="btn btn-block btn-outline-primary">
                Add To Cart
            </button>

        }
    </div>
</div>

Demo.WebUI/Views/Home/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>test</h2>

<p>hi</p>